const artists=[{name:'Akira Mizuno',desc:'Neo cinematic / soft narrative light',initials:'AK',color:'#f3ad7a',seed:'42190831'},{name:'Yuki Tanaka',desc:'Dreamy anime / airy atmosphere',initials:'YT',color:'#b8a4ff',seed:'83910274'},{name:'Mara Voss',desc:'Editorial noir / vintage grain',initials:'MV',color:'#8db9ff',seed:'16740218'},{name:'Eliot Park',desc:'Painterly fantasy / oil texture',initials:'EP',color:'#9bd7b7',seed:'50881239'}];
const ideas=['Rainy Tokyo rooftop, red coat, neon reflections, cinematic composition','An old library floating above clouds, golden afternoon light, fantasy illustration','White dog outside a late-night convenience store, wet street, colorful signs','Moon greenhouse full of luminous ferns, transparent dome, sci-fi concept art'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={gallery:JSON.parse(localStorage.getItem('novelGallery')||'[]'),artist:0,lastImage:null};
function toast(m){const n=$('#toast');if(!n)return;n.textContent=m;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
function save(){localStorage.setItem('novelGallery',JSON.stringify(state.gallery));if($('#galleryCount'))$('#galleryCount').textContent=state.gallery.length}
function artImage(i){const c=[['#d67456','#251d2d','#f2c078'],['#6952a8','#18253e','#eeb2cf'],['#283a4c','#be734f','#e4cda1'],['#3c745f','#182c29','#d4b66e']][i%4];const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 900"><defs><linearGradient id="g"><stop stop-color="${c[0]}"/><stop offset=".55" stop-color="${c[1]}"/><stop offset="1" stop-color="${c[2]}"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="70%" cy="30%" r="25%" fill="${c[2]}" opacity=".3"/><path d="M0 75% Q30% 58% 55% 74% T100% 65% V100% H0Z" fill="#101319" opacity=".45"/></svg>`;return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
function applyArtist(){const a=artists[state.artist];$('#artistName').textContent=a.name;$('#artistDesc').textContent=a.desc;$('#seedInput').value=a.seed;const v=$('.artist-avatar');if(v){v.textContent=a.initials;v.style.background=a.color}}
function card(x){return`<div class="image-card"><img src="${x.src}"/><div class="card-overlay">${x.prompt.slice(0,42)}</div></div>`}
function renderRecent(){const a=state.gallery.slice(0,4);$('#recentGrid').innerHTML=a.length?a.map(card).join(''):[0,1,2,3].map(i=>`<div class="image-card"><img src="${artImage(i)}"/></div>`).join('')}
function renderGallery(){$('#galleryGrid').innerHTML=state.gallery.length?state.gallery.map(card).join(''):'<div class="empty-state" style="grid-column:1/-1">还没有作品，先生成一张吧。</div>'}
function renderPresets(){const q=($('#presetSearch').value||'').toLowerCase();$('#presetList').innerHTML=artists.filter(a=>a.name.toLowerCase().includes(q)).map((a,i)=>`<div class="preset-list-item ${i===state.artist?'active':''}" data-artist="${i}"><div class="artist-avatar" style="background:${a.color}">${a.initials}</div><div><strong>${a.name}</strong><small>${a.desc}</small></div></div>`).join('');$$('.preset-list-item').forEach(n=>n.onclick=()=>{state.artist=+n.dataset.artist;renderPresets()});const a=artists[state.artist];$('#presetDetail').innerHTML=`<p class="eyebrow">ARTIST PRESET</p><h2>${a.name}</h2><p>${a.desc}</p><button class="primary-btn use-preset">应用到创作台 →</button>`;$('.use-preset').onclick=()=>{applyArtist();navigate('studio')}}
function navigate(v){$$('.view').forEach(n=>n.classList.add('hidden'));const t=$(`#${v}View`);if(t)t.classList.remove('hidden');if(v==='gallery')renderGallery();if(v==='presets')renderPresets()}
async function generate(){const prompt=$('#promptInput').value.trim()||ideas[Math.floor(Math.random()*ideas.length)];const button=$('#generateBtn');button.disabled=true;$('#previewStatus').textContent='生成中…';$('#previewCanvas').innerHTML='<div class="loading-shimmer"></div>';let src;const api=JSON.parse(localStorage.getItem('novelApi')||'{}');try{if(api.key&&api.endpoint&&window.JSZip){const r=await fetch(api.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${api.key}`},body:JSON.stringify({input:prompt,action:'generate',model:'nai-diffusion-4-5-full',parameters:{width:640,height:960,steps:+$('#stepsRange').value,scale:+$('#guidanceRange').value,seed:$('#seedInput').value==='随机'?Math.floor(Math.random()*99999999):+$('#seedInput').value,n_samples:1,negative_prompt:$('#negativeInput').value}})});if(r.ok){const z=await JSZip.loadAsync(await r.arrayBuffer());const f=z.file(/\.(png|jpg|jpeg)$/i)[0];if(f)src=URL.createObjectURL(await f.async('blob'))}}}catch(e){toast('NovelAI 直连失败，使用本地预览')}src=src||artImage(state.gallery.length);state.lastImage=src;state.gallery.unshift({id:Date.now(),src,prompt,artist:artists[state.artist].name,ratio:$('#ratioSelect').value,favorite:false});$('#previewCanvas').innerHTML=`<img class="generated-preview" src="${src}"/>`;$('#canvasMeta').textContent=`NovelAI · ${$('#ratioSelect').value} · ${artists[state.artist].name}`;$('#savePreviewBtn').disabled=false;$('#previewStatus').textContent='生成完成';button.disabled=false;save();renderRecent();toast('作品已生成')}
document.addEventListener('DOMContentLoaded',()=>{save();renderRecent();applyArtist();$('#promptInput').oninput=()=>$('#tokenCount').textContent=`${$('#promptInput').value.length} / 2000`;$('#generateBtn').onclick=generate;$('#randomPromptBtn').onclick=()=>{$('#promptInput').value=ideas[Math.floor(Math.random()*ideas.length)];$('#promptInput').oninput()};$('#enhanceBtn').onclick=()=>{$('#promptInput').value+=', cinematic lighting, intricate details';$('#promptInput').oninput()};$('#clearPromptBtn').onclick=()=>{$('#promptInput').value='';$('#promptInput').oninput()};$('#randomSeedBtn').onclick=()=>$('#seedInput').value=Math.floor(Math.random()*99999999);$('#stepsRange').oninput=e=>$('#stepsOutput').textContent=e.target.value;$('#guidanceRange').oninput=e=>$('#guidanceOutput').textContent=e.target.value;$('#advancedToggle').onclick=()=>$('#advancedContent').classList.toggle('open');$('#savePreviewBtn').onclick=()=>{if(state.gallery[0]){state.gallery[0].favorite=true;save();toast('已收藏')}};$$('[data-view]').forEach(n=>n.onclick=()=>navigate(n.dataset.view));$('#managePresetsBtn').onclick=()=>navigate('presets');$('#presetSearch').oninput=renderPresets;$('#apiSettingsBtn').onclick=()=>$('#apiModal').classList.remove('hidden');$('#closeApiModal').onclick=()=>$('#apiModal').classList.add('hidden');$('#saveApiBtn').onclick=()=>{localStorage.setItem('novelApi',JSON.stringify({endpoint:$('#apiEndpoint').value.trim(),key:$('#apiKey').value.trim()}));$('#apiModal').classList.add('hidden');toast('连接设置已保存')};$('#clearApiBtn').onclick=()=>{localStorage.removeItem('novelApi');$('#apiKey').value='';toast('已清除连接')}})
